site_name: xv6-Chinese

repo_name: xv6-book-Chinese
repo_url: https://github.com/Misaka-9982-coder/xv6-book-Chinese

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - 操作系统:
      - 0. 前言和致谢: "S081/0. 前言和致谢.md"
      - 1. 操作系统接口.md: "S081/1. 操作系统接口.md"
      - 2. 操作系统架构.md: "S081/2. 操作系统架构.md"
      - 3. 页表.md: "S081/3. 页表.md"
      - 4. trap 与系统调用.md: "S081/4. trap 与系统调用.md"
      - 5. 中断和设备驱动程序.md: "S081/5. 中断和设备驱动程序.md"
      - 6. 锁.md: "S081/6. 锁.md"
      - 7. 调度.md: "S081/7. 调度.md"
      - 8. 文件系统.md: "S081/8. 文件系统.md"
      - 9. 再次探讨并发性.md: "S081/9. 再次探讨并发性.md"