site_name: doc-zh

repo_name: doc-zh
repo_url: https://github.com/Misaka-9982-coder/doc-zh

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - 操作系统:
      - 0. 前言和致谢: "S081/0. 前言和致谢.md"
      - 1. 操作系统接口: "S081/1. 操作系统接口.md"
      - 2. 操作系统架构: "S081/2. 操作系统架构.md"
      - 3. 页表: "S081/3. 页表.md"
      - 4. trap 与系统调用: "S081/4. trap 与系统调用.md"
      - 5. 中断和设备驱动程序: "S081/5. 中断和设备驱动程序.md"
      - 6. 锁: "S081/6. 锁.md"
      - 7. 调度: "S081/7. 调度.md"
      - 8. 文件系统: "S081/8. 文件系统.md"
      - 9. 再次探讨并发性: "S081/9. 再次探讨并发性.md"
  
  - 编译原理:
      - contents: "craftinginterpreters/0_00.contents/contents.md"
      - acknowledgements: "craftinginterpreters/0_01.acknowledgements/acknowledgements.md"
      - Introduction: "craftinginterpreters/1_01.Introduction/Introduction.md"
      - A Map of the Territory: "craftinginterpreters/1_02.A Map of the Territory/A Map of the Territory.md"
      - The Lox Language: "craftinginterpreters/1_03.The Lox Language/The Lox Language.md"
      - A TREE-WALK INTERPRETER: "craftinginterpreters/2_00.A TREE-WALK INTERPRETER/A TREE-WALK INTERPRETER.md"
      - Scanning: "craftinginterpreters/2_04.Scanning/Scanning.md"
      - Representing Code: "craftinginterpreters/2_05.Representing Code/Representing Code.md"
      - Parsing Expressions: "craftinginterpreters/2_06.Parsing Expressions/Parsing Expressions.md"
      - Evaluating Expressions: "craftinginterpreters/2_07.Evaluating Expressions/Evaluating Expressions.md"
      - Statements and State: "craftinginterpreters/2_08.Statements and State/Statements and State.md"
      - Control Flow: "craftinginterpreters/2_09.Control Flow/Control Flow.md"
      - Functions: "craftinginterpreters/2_10.Functions/Functions.md"
      - Resolving and Binding: "craftinginterpreters/2_11.Resolving and Binding/Resolving and Binding.md"
      - Classes: "craftinginterpreters/2_12.Classes/Classes.md"
      - Inheritance: "craftinginterpreters/2_13.Inheritance/Inheritance.md"
      - A BYTECODE VIRTUAL MACHINE: "craftinginterpreters/3_00.A BYTECODE VIRTUAL MACHINE/A BYTECODE VIRTUAL MACHINE.md"
      - Chunks of Bytecode: "craftinginterpreters/3_14.Chunks of Bytecode/Chunks of Bytecode.md"
      - A Virtual Machine: "craftinginterpreters/3_15.A Virtual Machine/A Virtual Machine.md"
      - Scanning on Demand: "craftinginterpreters/3_16.Scanning on Demand/Scanning on Demand.md"
      - Compiling Expressions: "craftinginterpreters/3_17.Compiling Expressions/Compiling Expressions.md"
      - Types of Values: "craftinginterpreters/3_18.Types of Values/Types of Values.md"
      - Strings: "craftinginterpreters/3_19.Strings/Strings.md"
      - Hash Tables: "craftinginterpreters/3_20.Hash Tables/Hash Tables.md"
      - Global Variables: "craftinginterpreters/3_21.Global Variables/Global Variables.md"
      - Local Variables: "craftinginterpreters/3_22.Local Variables/Local Variables.md"
      - Jumping Back and Forth: "craftinginterpreters/3_23.Jumping Back and Forth/Jumping Back and Forth.md"
      - Calls and Functions: "craftinginterpreters/3_24.Calls and Functions/Calls and Functions.md"
      - Closures: "craftinginterpreters/3_25.Closures/Closures.md"
      - Garbage Collection: "craftinginterpreters/3_26.Garbage Collection/Garbage Collection.md"
      - Classes and Instances: "craftinginterpreters/3_27.Classes and Instances/Classes and Instances.md"
      - Methods and Initializers: "craftinginterpreters/3_28.Methods and Initializers/Methods and Initializers.md"
      - Superclasses: "craftinginterpreters/3_29.Superclasses/Superclasses.md"
      - Optimization: "craftinginterpreters/3_30.Optimization/Optimization.md"
      - A1.Appendix I Lox Grammar: "craftinginterpreters/4_01.A1.Appendix I Lox Grammar/A1.Appendix I Lox Grammar.md"
      - A2.Appendix II Generated Syntax Tree Classes: "craftinginterpreters/4_02.A2.Appendix II Generated Syntax Tree Classes/A2.Appendix II Generated Syntax Tree Classes.md"